version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: books
